RESULTS_FOLDER_PATH = './results/'
RANDOM_SEED = 42
SIMULATIONS_PER_MODEL = 10

# Grid
GRID_WIDTH = 6
GRID_HEIGHT = 5
ROAD_LENGTH = 1

# Intersections
NEIGHBOUR_PROBABILITY = 1  # The probability of an intersection being connected to a neighbouring one

# Vehicles
VEHICLE_MIN_ROADS = 2
VEHICLE_MAX_ROADS = 5
MIN_VEHICLES = 3
MAX_VEHICLES = 4
DEFAULT_DIRECTION = 0

# Run
MAX_VEHICLES_PER_STEP = 4
